title = "Sean Dockray"

[author]
name = "Sean Dockray"
image = "img/author.jpg"
headline = "a headline can be changed"
bio = "a one line bio right here"
links = [
  { twitter = "https://twitter.com/seandockray" }
]
