[[main]]
  name = "projects"
  pageRef = "projects/overview"
  weight = 2

[[main]]
  name = "writing"
  pageRef = "writing/overview"
  weight = 3

[[main]]
  name = "about"
  pageRef = "about"
  weight = 10

[[main]]
  name = "contact"
  pageRef = "contact"
  weight = 20
